services:
  - type: web
    name: student-portal
    env: docker
    plan: free
    healthCheckPath: /health.php
    autoDeploy: true
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: OPEN_SIS_TITLE
        value: GS Student Portal
